sudo: required

language: cpp

os:
  - linux
  - osx
dist: bionic

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - git
    - g++
    - cmake
    - libboost-dev
    - libyaml-cpp-dev

cache:
  # Caching Ubuntu packages
  apt: true

before_script:
  - env | sort
  - date -u
  - uname -a
  - bash ./scripts/build_dependencies.sh

script:
  # build
  - pwd
  - bash ./scripts/build.sh

after_failure:
  - cat build/CMakeFiles/CMakeOutput.log

