language: cpp

os: linux
dist: bionic

compiler: gcc
addons:
  apt:
    packages:
    - git
    - g++
    - cmake
    - libboost-dev
    - libyaml-cpp-dev

cache:
  # Caching Ubuntu packages
  apt: true

before_script:
  - env | sort
  - date -u
  - uname -a
  # Exit immediately if a command exits with a non-zero status
  - set -e
  # Print commands and their arguments as they are executed.
  - set -x

  - echo "=== Build libear ==="
  - cd ${TRAVIS_BUILD_DIR}
  - git clone --recursive https://github.com/ebu/libear.git && cd libear/
  - mkdir build && cd build
  - cmake ..
  - make
  - make install

  - echo "=== Build libadm ==="
  - cd ${TRAVIS_BUILD_DIR}
  - git clone https://github.com/IRT-Open-Source/libadm.git && cd libadm/
  - mkdir build && cd build
  - cmake ..
  - make
  - make install

  - echo "=== Build libbw64 ==="
  - cd ${TRAVIS_BUILD_DIR}
  - git clone https://github.com/IRT-Open-Source/libbw64.git && cd libbw64/
  - mkdir build && cd build
  - cmake ..
  - make
  - make install

script:
  # build
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake ..
  - make
  - make install

after_failure:
  - cd ${TRAVIS_BUILD_DIR}
  - cat build/CMakeFiles/CMakeOutput.log

